# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9399c00a590d15bf49125fc68fa8cafd038c417274951c5b2713c64e1130b1290a8e51effc49940ecc741a02c654af709f372459cc8ac4edd18ceedfeb33202c

test:
  secret_key_base: 92a209c8eb96eed623eb2b6900ec5e5704bef6a03d03a5a0fb98b4783bda9e09013c3ef1c59c100740f8ee4fe749653b50453dbdcb9f38616b00c9d86e677744

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
